- name: Create container
  community.docker.docker_container:
    name: watchtower
    image: "ghcr.io/containrrr/watchtower"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped
    state: started