- name: Manages Monitoring agents on all hosts
  hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - prometheus.prometheus.node_exporter
    - docker_grafana_agent

  vars_files:
    - ../../.vault

  vars:
    pip_install_packages:
      - name: docker

    node_exporter_enabled_collectors:
      - systemd
      - textfile:
          directory: "{{ node_exporter_textfile_dir }}"
      - filesystem:
          ignored-mount-points: ^/(dev|proc|sys|var/lib/docker/(containers|devicemapper|overlay2)/.+)($|/)
          ignored-fs-types: "^(sys|proc|auto|te?mp|ram|ns)fs$"

  tasks:
    # --grant-all-permissions is true by default
    - name: Install loki docker driver
      community.docker.docker_plugin:
        plugin_name: grafana/loki-docker-driver:latest
        alias: loki
        state: enable

    - name: Configure default logging driver
      ansible.builtin.copy:
        src: files/docker-daemon.json
        dest: /etc/docker/daemon.json
        mode: "0644"
  
    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
