- name: Manages Monitoring agents on all hosts
  hosts: all
  roles:
    - prometheus.prometheus.node_exporter
  vars:
    node_exporter_enabled_collectors:
      - systemd
      - textfile:
          directory: "{{ node_exporter_textfile_dir }}"
      - filesystem:
          ignored-mount-points: ^/(dev|proc|sys|var/lib/docker/(containers|devicemapper|overlay2)/.+)($|/)
          ignored-fs-types: "^(sys|proc|auto|te?mp|ram|ns)fs$"
