- name: Loki Grafana Turbo Mimir stack management
  hosts: monitoring
  vars:
    org_name: 'Homelab'
    pip_install_packages:
      - name: docker
  
  vars_files:
    - ../../.vault

  roles:
    - geerlingguy.docker
    - trox.docker_watchtower
    - geerlingguy.pip
    - trox.lgtm_docker