- name: Update prometheus rules
  hosts: monitoring

  vars_files:
    - ../../.vault

  tasks:
    - name: Include prom-config
      ansible.builtin.include_role:
        name: docker_lgtm
        tasks_from: prom-config
