[docker]
monitoring.lan
db-mariadb.lan
generic.lan
gameserver.lan
plexbox.lan
downloader.lan
adguard.lan

[homeassistant]
homeassistant.lan

[monitoring]
monitoring.lan

[mariadb]
db-mariadb.lan

[synology]
synology.lan