- name: Update grafana provisionings
  ansible.builtin.copy:
    src: "files/grafana/"
    dest: "{{ stack_location }}/grafana/"
    mode: "0644"
  register: provisionings
  notify: Restart grafana

- name: Template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ stack_location }}/grafana/{{ item.path | regex_replace('\\.j2$', '') }}"
    force: true
    mode: "0644"
  with_community.general.filetree: "{{ ['templates/grafana'] }}"
  when: item.state == 'file'
  register: templates
  notify: Restart grafana
