- name: Clean up old Grafana provisionings
  ansible.builtin.file:
    path: "{{ stack_location }}/grafana/provisioning"
    state: absent

- name: Copy files
  ansible.builtin.copy:
    src: files/
    dest: "{{ stack_location }}"
    mode: "0644"

- name: Template Directory structure
  ansible.builtin.file:
    state: directory
    dest: "{{ stack_location }}/{{ item.path }}"
    mode: "755"
  with_community.general.filetree: "{{ ['templates/'] }}"
  when: item.state == 'directory'

- name: Template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ stack_location }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    force: true
    mode: "0644"
  with_community.general.filetree: "{{ ['templates/'] }}"
  when: item.state == 'file'

- name: Deploy compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ stack_location }}"
    recreate: always
