- name: Update prometheus rules
  ansible.builtin.copy:
    src: "files/prometheus/rules/"
    dest: "{{ stack_location }}/prometheus/rules/"
    mode: "0644"
  register: rules
  

- name: Template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ stack_location }}/prometheus/{{ item.path | regex_replace('\\.j2$', '') }}"
    force: true
    mode: "0644"
  with_community.general.filetree: "{{ ['templates/prometheus'] }}"
  when: item.state == 'file'
  register: templates

- name: Restart prometheus
  community.docker.docker_compose_v2:
    project_src: "{{ stack_location }}"
    services:
      - prometheus
    state: restarted
  when: rules.changed or templates.changed