- name: Update prometheus rules
  ansible.builtin.copy:
    src: "files/prometheus/rules/"
    dest: "{{ stack_location }}/prometheus/rules/"
    mode: "0644"
  register: rules
  notify: Restart prometheus

- name: Template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ stack_location }}/prometheus/{{ item.path | regex_replace('\\.j2$', '') }}"
    force: true
    mode: "0644"
  with_community.general.filetree: "{{ ['templates/prometheus'] }}"
  when: item.state == 'file'
  notify: Restart prometheus
