{
 "title": "Homelab Vitals",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "VM Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT \"cpu\", \"mem\", \"maxmem\", \"host\" FROM \"system\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ],
      [
       { "params": [ "mem" ], "type": "field" }
      ],
      [
       { "params": [ "maxmem" ], "type": "field" }
      ],
      [
       { "params": [ "host" ], "type": "field" }
      ],
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Pools",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"nodename\"] == \"pve\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \n    _time: r._time,\n    _measurement: r.measurement,\n    _field: \"used_perc\",\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\n     }))\n  |> drop(columns: [\"avail\",\"used\"])\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"pve.trox.lan:9100\",job=\"node_exporter\"} - node_boot_time_seconds{instance=\"pve.trox.lan:9100\",job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"pve.trox.lan:9100\",job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"pve.trox.lan:9100\",job=\"node_exporter\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"pve.trox.lan:9100\",job=\"node_exporter\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"pve.trox.lan:9100\",job=\"node_exporter\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "NUC Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius) by (instance, chip)",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"pve.trox.lan:9100\",job=\"node_exporter\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"pve.trox.lan:9100\",job=\"node_exporter\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{instance=\"pve.trox.lan:9100\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=\"pve.trox.lan:9100\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Internet Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "download_speed_bps", "legendFormat": "Download Speed" },
    { "expr": "upload_speed_bps", "legendFormat": "Upload Speed" }
   ]
  },
  { "title": "NAS Status", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "NAS Storage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "raidTotalSize{job='snmp'}", "legendFormat": "Total Size" },
    {
     "expr": "(raidTotalSize{job='snmp'}-raidFreeSize{job='snmp'})",
     "legendFormat": "Used"
    },
    { "expr": "raidFreeSize{job='snmp'}", "legendFormat": "Free" },
    { "expr": "raidStatus{job='snmp'}", "legendFormat": "Free" },
    {
     "expr": "((raidTotalSize{job='snmp'}-raidFreeSize{job='snmp'})/raidTotalSize{job='snmp'})*100",
     "legendFormat": "Usage by Percent"
    }
   ]
  },
  {
   "title": "NAS Drives",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "diskIndex{job='snmp'}" },
    { "expr": "diskID{job='snmp'}" },
    { "expr": "diskType{job='snmp'}" },
    { "expr": "diskStatus{job='snmp'}" },
    { "expr": "diskModel{job='snmp'}" },
    { "expr": "diskTemperature{job='snmp'}" }
   ]
  }
 ]
}