{
 "title": "Homelab Vitals",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "Homelab Status",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance_friendly_name) (irate(node_cpu_seconds_total{job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / on(instance_friendly_name) group_left sum by (instance_friendly_name)((irate(node_cpu_seconds_total{job=\"node_exporter\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\"} - node_memory_MemFree_bytes - (node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{job=\"node_exporter\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{job=\"node_exporter\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_time_seconds{job=\"node_exporter\"} - node_boot_time_seconds{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Pools",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"nodename\"] == \"pve\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \n    _time: r._time,\n    _measurement: r.measurement,\n    _field: \"used_perc\",\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\n     }))\n  |> drop(columns: [\"avail\",\"used\"])\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"pve.lan:9100\",job=\"node_exporter\"} - node_boot_time_seconds{instance=\"pve.lan:9100\",job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"pve.lan:9100\",job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"pve.lan:9100\",job=\"node_exporter\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"pve.lan:9100\",job=\"node_exporter\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"pve.lan:9100\",job=\"node_exporter\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"pve.lan:9100\",job=\"node_exporter\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"pve.lan:9100\",job=\"node_exporter\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{instance=\"pve.lan:9100\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=\"pve.lan:9100\",job=\"node_exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "NUC Temperatures",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"pve.lan:9100\"}) by (instance, chip)",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"pve.lan:9100\",job=\"node_exporter\",device=\"enp114s0\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"pve.lan:9100\",job=\"node_exporter\",device=\"enp114s0\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "NAS Status", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "NAS Storage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "raidTotalSize{job='snmp'}", "legendFormat": "Total Size" },
    {
     "expr": "(raidTotalSize{job='snmp'}-raidFreeSize{job='snmp'})",
     "legendFormat": "Used"
    },
    { "expr": "raidFreeSize{job='snmp'}", "legendFormat": "Free" },
    { "expr": "raidStatus{job='snmp'}", "legendFormat": "Free" },
    {
     "expr": "((raidTotalSize{job='snmp'}-raidFreeSize{job='snmp'})/raidTotalSize{job='snmp'})*100",
     "legendFormat": "Usage by Percent"
    }
   ]
  },
  {
   "title": "NAS Drives",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    { "expr": "diskIndex{job='snmp'}" },
    { "expr": "diskID{job='snmp'}" },
    { "expr": "diskType{job='snmp'}" },
    { "expr": "diskStatus{job='snmp'}" },
    { "expr": "diskModel{job='snmp'}" },
    { "expr": "diskTemperature{job='snmp'}" }
   ]
  },
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 32 },
   "targets": [
    { "expr": "qbittorrent_torrent_info" }
   ]
  },
  {
   "title": "Global Download Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes"
    }
   ]
  },
  {
   "title": "NZB Download speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_queue_download_rate_bytes_per_second"
    }
   ]
  },
  {
   "title": "Global Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbittorrent_global_ratio  " }
   ]
  },
  {
   "title": "NZB Queue total size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sabnzbd_queue_total_size_bytes" }
   ]
  },
  {
   "title": "Global Upload Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_upload_speed_bytes"
    }
   ]
  },
  {
   "title": "NZB Download time remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sabnzbd_queue_remaining_seconds"
    }
   ]
  },
  {
   "title": "Printer Ink",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "%",
     "query": "import \"regexp\"\r\n\r\nfrom(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"%\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"domain\"] == \"sensor\")\r\n  |> filter(fn: (r) => r[\"entity_id\"] == \"hl_3170cdw_black_toner_remaining\" or r[\"entity_id\"] == \"hl_3170cdw_cyan_toner_remaining\" or r[\"entity_id\"] == \"hl_3170cdw_magenta_toner_remaining\" or r[\"entity_id\"] == \"hl_3170cdw_yellow_toner_remaining\")\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"friendly_name\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"entity_id\", \"_field\", \"domain\", \"source\"])\r\n  |> rename(fn: (column) => regexp.replaceAllString(r: /.*(Black|Cyan|Magenta|Yellow).*/, v: column, t: \"$1\"))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "domain::tag", "operator": "=", "value": "sensor" },
      {
       "condition": "AND",
       "key": "friendly_name::tag",
       "operator": "=",
       "value": "Brother HL-3170CDW series Black Toner Cartridge"
      },
      {
       "condition": "OR",
       "key": "friendly_name::tag",
       "operator": "=",
       "value": "Brother HL-3170CDW series Cyan Toner Cartridge"
      },
      {
       "condition": "OR",
       "key": "friendly_name::tag",
       "operator": "=",
       "value": "Brother HL-3170CDW series Magenta Toner Cartridge"
      },
      {
       "condition": "OR",
       "key": "friendly_name::tag",
       "operator": "=",
       "value": "Brother HL-3170CDW series Yellow Toner Cartridge"
      }
     ]
    }
   ]
  }
 ]
}