- name: Manage apt packages
  hosts: all
  tasks:
    - name: Update & Upgrade
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        install-recommends: true
        purge: true
        autoremove: true
        cache_valid_time: 86400 # One day

    - name: Default apt packages
      ansible.builtin.apt:
        pkg:
          - htop
          - iputils-ping
          - net-tools
          - lsof
        state: present
