- name: Manages Docker
  hosts: docker
  become: true
  roles:
    - geerlingguy.docker
    - prometheus.prometheus.cadvisor
    - docker_watchtower

  pre_tasks:
    - name: Create docker group
      ansible.builtin.group:
        name: docker
        gid: 1000
    - name: Create docker user
      ansible.builtin.user:
        name: docker
        group: docker
        uid: 1000

  tasks:
    - name: Update cadvisor service template
      ansible.builtin.lineinfile:
        path: /etc/systemd/system/cadvisor.service
        line: "    '--raw_cgroup_prefix_whitelist=/docker/' \\"
        insertafter: '.*--listen_ip=.*'
    - name: Restart cadvisor
      ansible.builtin.systemd:
        name: cadvisor
        daemon_reload: true
        state: restarted
