- name: Manage Media Server
  hosts: mediaserver

  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - docker_watchtower
    - mediaserver

  vars:
    pip_install_packages:
      - name: docker

  vars_prompt:
    - name: gluetun_vpn_user
      prompt: VPN Username
      private: false
    - name: gluetun_vpn_password
      prompt: VPN Password
