- name: Manages NextCloud AIO as Docker Container installation
  hosts: nextcloud
  tasks:
    - name: Prepare hosts
      ansible.builtin.file:
        dest: '/var/docker/nextcloud/{{ item }}'
        mode: '0644'
        state: directory
      loop:
        - data
        - config
    - name: Create container
      community.docker.docker_container:
        name: nextcloud-aio-mastercontainer
        image: nextcloud/all-in-one:latest
        env:
          NEXTCLOUD_DATADIR: '/var/nextcloud-data'
          APACHE_PORT: '11000'
          APACHE_IP_BINDING: '0.0.0.0'
          SKIP_DOMAIN_VALIDATION: 'true'
        volumes:
          - 'nextcloud_aio_mastercontainer:/mnt/docker-aio-config'
          - '/mnt/synology:/var/nextcloud-data'
          - '/var/run/docker.sock:/var/run/docker.sock'
        restart_policy: unless-stopped
        ports:
          - '8080:8080'
        recreate: true
