- name: Manage wg-easy
  hosts: wireguard
  tasks:
    - name: Create config directory
      ansible.builtin.file:
        dest: /root/.wg-easy
        mode: "0775"
        state: directory
    - name: Run Docker Container
      community.docker.docker_container:
        name: wg-easy
        image: ghcr.io/wg-easy/wg-easy
        env:
          - WG_HOST: "{{ wg_public_host }}"
          - PASSWORD: "{{ wg_admin_password }}"
          - WG_DEFAULT_ADDRESS: "192.168.5.x"
        volumes:
          - "/root/.wg-easy:/etc/wireguard"
        ports:
          - "51820:51820/udp"
          - "51821:51821/tcp"
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        sysctls:
          - "net.ipv4.conf.all.src_valid_mark=1"
          - "net.ipv4.ip_forward=1"
        restart_policy: unless-stopped
        recreate: true
        state: started
